version: '3.1'

services:
  test_mysql:
    container_name: "pipelinewise-tap-mysql-db"
    image: mariadb:10.2.26
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-passwd
      MYSQL_DATABASE: tap_mysql_test
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --binlog-format=ROW
    networks:
      - dev-net

networks:
  dev-net:
    ipam:
      driver: default
      config:
        - subnet: "185.16.238.0/24"